In [1]:
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np

In [2]:
arr1 = np.array([12,22,37,32,29,42])
arr2 = np.array([82,78,53])
arr3 = np.array([12,22,37,32,29,42,82,78,53])

In [3]:
평균1  = np.mean(arr1)
분산1 = np.var(arr1)
편차1 = np.std(arr1)
print("평균1", 평균1,  "분산1:", 분산1, "편차1:", 편차1)
평균2  = np.mean(arr2)
분산2 = np.var(arr2)
편차2 = np.std(arr2)
print("평균2", 평균2,  "분산2:", 분산2, "편차2:", 편차2)
평균3  = np.mean(arr3)
분산3 = np.var(arr3)
편차3 = np.std(arr3)
print("평균3", 평균3,  "분산3:", 분산3 , "편차3:", 편차3)

평균1 29.0 분산1: 96.66666666666667 편차1: 9.83192080250175
평균2 71.0 분산2: 164.66666666666666 편차2: 12.832251036613439
평균3 43.0 분산3: 511.3333333333333 편차3: 22.612680808195506


In [4]:
분산1 = ((arr1 - 평균1)**2).sum() * 1/len(arr1)
분산2 = ((arr2 - 평균2)**2).sum() * 1/len(arr2)
분산3 = ((arr3 - 평균3)**2).sum() * 1/len(arr3)
print(분산1, 분산2, 분산3)

96.66666666666667 164.66666666666666 511.3333333333333


In [5]:
편차1 = np.sqrt(분산1)
편차2 = np.sqrt(분산2)
편차3 = np.sqrt(분산3)
print(편차1, 편차2, 편차3)

9.83192080250175 12.832251036613439 22.612680808195506


In [6]:
표준화Z1 = (arr1 - 평균1)/편차1
표준화Z2 = (arr2 - 평균2)/편차2
표준화Z3 = (arr3 - 평균3)/편차3
print(표준화Z1)
print(표준화Z2)
print(표준화Z3)

[-1.72906193 -0.71196668  0.8136762   0.30512858  0.          1.32222383]
[ 0.85721515  0.54550055 -1.4027157 ]
[-1.3709122  -0.92868246 -0.26533785 -0.48645272 -0.61912164 -0.04422297
  1.72469599  1.5478041   0.44222974]


In [7]:
print(np.mean(표준화Z1) , np.std(표준화Z1))
print(np.mean(표준화Z2) , np.std(표준화Z2))
print(np.mean(표준화Z3) , np.std(표준화Z3))

0.0 1.0
0.0 1.0
0.0 0.9999999999999999


In [10]:
import scipy as sc
import scipy.stats as ss 

In [11]:
print(sc.mean(arr1), sc.var(arr1), sc.std(arr1))
print(sc.mean(arr2), sc.var(arr2), sc.std(arr2))
print(sc.mean(arr3), sc.var(arr3), sc.std(arr3))

29.0 96.66666666666667 9.83192080250175
71.0 164.66666666666666 12.832251036613439
43.0 511.3333333333333 22.612680808195506


In [12]:
표준화1 = sc.stats.zscore(arr1)
표준화2 = sc.stats.zscore(arr2)
표준화3 = sc.stats.zscore(arr3)
print(표준화Z1)
print(표준화Z2)
print(표준화Z3)

[-1.72906193 -0.71196668  0.8136762   0.30512858  0.          1.32222383]
[ 0.85721515  0.54550055 -1.4027157 ]
[-1.3709122  -0.92868246 -0.26533785 -0.48645272 -0.61912164 -0.04422297
  1.72469599  1.5478041   0.44222974]


In [13]:
# 표준화 = 평균0, 분산1로 하는 변환
print(sc.mean(표준화Z1) , sc.std(표준화Z1))
print(sc.mean(표준화Z2) , sc.std(표준화Z2))
print(sc.mean(표준화Z3) , sc.std(표준화Z3))

0.0 1.0
0.0 1.0
0.0 0.9999999999999999


In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()
scaler_arr1 = scaler.fit_transform(arr1.reshape(-1,1))
scaler_arr2 = scaler.fit_transform(arr2.reshape(-1,1))
scaler_arr3 = scaler.fit_transform(arr3.reshape(-1,1))
print(scaler_arr1.flatten())
print(scaler_arr2.flatten())
print(scaler_arr3.flatten())

[-1.72906193 -0.71196668  0.8136762   0.30512858  0.          1.32222383]
[ 0.85721515  0.54550055 -1.4027157 ]
[-1.3709122  -0.92868246 -0.26533785 -0.48645272 -0.61912164 -0.04422297
  1.72469599  1.5478041   0.44222974]


In [16]:
print(np.mean(scaler_arr1), np.std(scaler_arr1))
print(np.mean(scaler_arr2), np.std(scaler_arr2))
print(np.mean(scaler_arr3), np.std(scaler_arr3))

0.0 1.0
0.0 1.0
0.0 0.9999999999999999


## 공분산, 상관계수

* 공분산 : -2개의 연속형 피쳐(독립=확률)간의 관계성 수치(통계량)
* 상관계수 : 공분산/ 편차 (-1~1)

In [19]:
import pandas as pd
import 

In [29]:
df = pd.read_csv("sample.txt", sep="/t")

In [30]:
df.head()

kor\teng
0  89.4\t79.6
1  84.2\t77.4
2  75.4\t69.4
3  32.6\t22.8
4  74.5\t68.2

In [31]:
kor = df.kor
eng = df.eng
N = df.shape[0]
kor_mean = sc.mean(kor)
eng_mean = sc.mean(eng)
print(kor_mean, eng_mean)

AttributeError: 'DataFrame' object has no attribute 'kor'

In [ ]:
공분산 = sum((kor - kor_mean)*(eng- eng_mean)) / (N-1)
print(공분산)

In [ ]:
공분산행렬 = sc.cov(kor, eng)
print(공분산행렬)

In [ ]:
피어슨상관계수 = 공분산 / (koe편차 * eng편차)

In [ ]:
kor분산 = sc.var(kor)
eng분산 = sc.var(eng)
피어슨상관계수 = 공분산 / sp.sqrt(kor편차 * eng편차)
print(피어슨상관계수)

kor표준편차 = sc.std(kor)
eng표준편차 = sc.std(eng)
피어슨상관계수 = 공분산 / (kor표준편차 * eng표준표준편차)
print(피어슨상관계수)