In [1]:
import numpy as np
data = np.random.randint(30, size=(6,5))

In [4]:
data

array([[10, 24, 12, 23,  7],
       [19, 11, 19, 24, 14],
       [15,  6, 12, 26,  7],
       [ 0, 15, 19, 15, 22],
       [ 0,  0, 14,  3, 22],
       [19, 18, 28, 16, 26]])

In [2]:
from sklearn.preprocessing import StandardScaler
data_standadized_skl = StandardScaler().fit_transform(data)

In [3]:
data_standadized_skl

array([[-0.06237829,  1.48700751, -0.95447998,  0.66440437, -1.24475183],
       [ 1.06043086, -0.16994372,  0.29827499,  0.79299876, -0.31118796],
       [ 0.56140458, -0.80723265, -0.95447998,  1.05018755, -1.24475183],
       [-1.30994401,  0.33988743,  0.29827499, -0.36435078,  0.75574218],
       [-1.30994401, -1.57197937, -0.59654999, -1.90748351,  0.75574218],
       [ 1.06043086,  0.72226079,  1.90895996, -0.23575639,  1.28920725]])

In [5]:
d2006 = [9.05,7.17,6.03,5.15,4.52,2.93,2.26]

In [7]:
n_2006 = np.array(d2006)

In [10]:
n_20061 = n_2006.reshape(-1, 1)

In [11]:
data_s = StandardScaler().fit_transform(n_20061)

In [12]:
data_s

array([[ 1.71144743],
       [ 0.8531148 ],
       [ 0.33263651],
       [-0.06913621],
       [-0.35676896],
       [-1.08269921],
       [-1.38859435]])